datasets:
  cc_sbu:
    data_type: images # [images|videos|features]
    build_info:      
      annotations:
        train:
          path:
               - ${env:DATA_DIR}\\filter_cap.json
      images:
        train:
          path:
               - ${env:DATA_DIR}\\image
