datasets:
  cc_sbu:
    data_type: images # [images|videos|features]
    build_info:      
      annotations:
        train:
          path:
               - ${env:DATA_DIR}/filter_cap.json
      images:
        train:
          path:
               #- ${env:DATA_DIR}/image
               - /swf_developer@t1v-n-4b3d9bc9-w-0:~/sample_2
               
