name: certifiedgpt-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.9
  - cudatoolkit
  - pip  
  - pip:
      - matplotlib==3.7.0
      - psutil==5.9.4
      - pyyaml==6.0
      - regex==2022.10.31
      - tqdm==4.64.1
      - scipy==1.7.3
      - scikit-image
      - statsmodels
      - huggingface-hub==0.18.0
      - iopath
      - tokenizers==0.13.2
      - transformers==4.30.0
      - timm==0.6.13
      - webdataset==0.2.48
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - decord==0.6.0
      - peft==0.2.0
      - sentence-transformers
      - gradio==3.47.1
      - accelerate==0.20.3
      - bitsandbytes==0.37.0
      - wandb
      - bert-score
