 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coco_vqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]
    build_info:
      questions:
        train:
          path:
              - /home/leonardosouza/projects/datasets/vqav2/questions/train/v2_OpenEnded_mscoco_train2014_questions.json
        val:
          path:
              - /home/leonardosouza/projects/datasets/vqav2/questions/val/v2_OpenEnded_mscoco_val2014_questions.json
      annotations:
        train:
          path:
              - /home/leonardosouza/projects/datasets/vqav2/annotations/train/v2_mscoco_train2014_annotations.json
        val:
          path:
              - /home/leonardosouza/projects/datasets/vqav2/annotations/val/v2_mscoco_val2014_annotations.json
      images:
        train:
          path:
            - /home/leonardosouza/projects/datasets/vqav2/images/train2014/all/
        val:
          path:
            - /home/leonardosouza/projects/datasets/vqav2/images/val2014/

  