datasets:
  coco_vqa:
    data_type: images
    build_info:
      questions:
        train:
          path:
              - ${env:DATA_DIR}/questions/train/v2_OpenEnded_mscoco_train2014_questions.json
        val:
          path:
              - ${env:DATA_DIR}/questions/val/v2_OpenEnded_mscoco_val2014_questions.json
        
      annotations:
        train:
          path:
              - ${env:DATA_DIR}/annotations/train/sample_v2_mscoco_train2014_annotations.json
        val:
          path:
              - ${env:DATA_DIR}/annotations/val/sample_v2_mscoco_val2014_annotations.json

      images:
        train:
          path:
              - /home/swf_developer/sample_10k/train
        val:
          path:
              - /home/swf_developer/sample_10k/val
