model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: ${env:MINIGPT_4}

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}
  
# Total batch_size should be multiple of 64
# featue dimension should be a multiple of 128
# https://cloud.google.com/tpu/docs/performance-guide
datasets:
  cc_sbu:
    batch_size: 16
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
        # mean: (0.6810068488121033, 0.6650859117507935, 0.6425760388374329)
        # std: (0.46608638763427734, 0.4719604253768921, 0.47924116253852844)
        min_scale: 0.5
        max_scale: 1.0      
    text_processor:
      train:
        name: "blip_caption"
      val:
        name: "blip_caption"
    sample_ratio: 115

run:
  agent: image_text_finetune
  max_epoch: 5  
  accumulated_gradients: 1
  patience: 1
  noise_level: 0
  checkpoint_name: "cc_sbu_finetuning"
  
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5 
  min_lr: 1e-5 
  warmup_lr: 1e-6 
  warmup_steps: 200
  iters_per_epoch: 200
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42  
  output_dir: ${env:OUTPUT_DIR}
  amp: True
  resume_ckpt_path: null
  evaluate: False
  train_splits: ["train"]
  has_val_split: False  

  device: "tpu"
  wandb: True
  wandb_api_key: ${env:WANDB_API_KEY}
  wandb_name: "finetuned_minigpt4_7b_stage2"  

  # DataLoader
  distributed: True  
  num_workers: 2 # n of workers to load data
