model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '  
  ckpt: ${env:MINIGPT_4}
    

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}


datasets:
  vqav2:
    batch_size: 12    
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
        # mean: (0.4612911641597748, 0.4411545395851135, 0.40491899847984314)
        # std: (0.49849939346313477, 0.4965251386165619, 0.49087637662887573)
        min_scale: 0.5
        max_scale: 1.0
      val:
        name: "blip2_image_val"
        image_size: 448
        # mean: (0.457837849855423, 0.4374278485774994, 0.4012486934661865)
        # std: (0.49821919202804565, 0.4960692822933197, 0.49015116691589355)
        min_scale: 0.5
        max_scale: 1.0
    text_processor:
      train:
        name: "blip_caption"
      val:
        name: "blip_caption"    

run:
  agent: image_text_finetune
  max_epoch: 1
  num_workers: 8
  accumulated_gradients: 1
  patience: 1
  noise_level: 0
      
  #Consider using other learning rate schedulers for small datasets
  # - Exponential Decay
  # - Plateau-Based Decay

  lr_sched: "linear_warmup_cosine_lr"  
  init_lr: 1e-5 # is max_lr in warmup_lr_schedule 
  min_lr: 1e-6 # used in cosine_lr_schedule
  warmup_lr: 1e-6 # is init_lr in warmup_lr_schedule  
  warmup_steps: 21
  iters_per_epoch: 7
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42  
  output_dir: ${env:OUTPUT_DIR}
    
  amp: True
  resume_ckpt_path: null
  evaluate: False
  train_splits: ["train"]
  has_val_split: true
  device: "tpu"
  wandb: True
  wandb_api_key: ${env:WANDB_API_KEY}
  wandb_name: "finetuned_certifiedgpt_vqa"  

#  world_size: 1
#  dist_url: "env://"
  distributed: True
