model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '/path/to/stage1/checkpoint/'

datasets:
  vqav2:
    batch_size: 64
    sample_size: 200 # if equals 0, all databset will be loaded
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
        mean: (0.48145466, 0.4578275, 0.40821073)
        std: (0.26862954, 0.26130258, 0.27577711)
        min_scale: 0.5
        max_scale: 1.0
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115

run:
  agent: image_text_finetune
  max_epoch: 1
  num_workers: 1
  warmup_steps: 5000
  iters_per_epoch: 5000
  init_lr: 1e-4
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42
  output_dir: "output/minigpt4_stage1_pretrain"
  amp: True
  resume_ckpt_path: null
  evaluate: False
  train_splits: [ "train" ]

  device: "cuda"

#  world_size: 1
#  dist_url: "env://"
#  distributed: False