model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
#  ckpt: '/path/to/stage1/checkpoint/'
  ckpt: null

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}
  

datasets:
  vqav2:
    batch_size: 1
    sample_size: 0 # if equals 0, all databset will be loaded
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
        mean: (0.48145466, 0.4578275, 0.40821073)
        std: (0.26862954, 0.26130258, 0.27577711)
        min_scale: 0.5
        max_scale: 1.0
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115

run:
  agent: image_text_finetune
  max_epoch: 1
  num_workers: 1
  warmup_steps: 5000
  iters_per_epoch: 5000
  init_lr: 1e-4
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42
  output_dir: "output/minigpt4_stage1_pretrain"
  amp: False
  resume_ckpt_path: null
  evaluate_only: False
  train_splits: [ "train" ]

  device: "cuda"

#  world_size: 1
#  dist_url: "env://"
#  distributed: False
