model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '/home/leonardosouza/storage/checkpoints/minigpt-4/prerained_minigpt4_7b.pth'

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}
  
  
  

datasets:
  vqav2:
    batch_size: 64
    noise_level: 0.25    
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 384
        mean: (0.4619535207748413, 0.44102171063423157, 0.4043944478034973)
        std: (0.4985503852367401, 0.4965093731880188, 0.4907744526863098)
        min_scale: 0.5
        max_scale: 1.0
      val:
        name: "blip2_image_val"
        image_size: 448
        mean: (0.4582795202732086, 0.4375796616077423, 0.40068480372428894)
        std: (0.4982563555240631, 0.4960884153842926, 0.4900372326374054)
        min_scale: 0.5
        max_scale: 1.0
    text_processor:
      train:
        name: "blip_caption"
      val:
        name: "blip_caption"    

run:
  agent: image_text_finetune
  max_epoch: 1
  num_workers: 1
  accumulated_gradients: 1
  patience: 10
      
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 5e-3 # 1e-2   # init_lr peak learning rate after warmup phase
  min_lr: 5e-4 #1e-3  #  minimum learning rate reached at the end of training
  warmup_lr: 5e-4 #1e-3  # starting learning rate for the warmup phase
  warmup_steps: 50
  iters_per_epoch: 10
  weight_decay: 0.1 #0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42
  output_dir: '/home/leonardosouza/storage/checkpoints/certifiedgpt/'
  amp: True
  resume_ckpt_path: null
  evaluate: False
  train_splits: ["train"]
  device: "tpu"
  wandb: True
  wandb_api_key: ${env:WANDB_API_KEY}

#  world_size: 1
#  dist_url: "env://"
  distributed: True
