model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: 'E:\pesquisa_ia\projetos\checkpoints\minigpt-4\prerained_minigpt4_7b.pth'

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}
  

datasets:
  vqav2:
    batch_size: 2
    sample_size: 200 # if equals 0, all databset will be loaded
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
        mean: (0.4619535207748413, 0.44102171063423157, 0.4043944478034973)
        std: (0.4985503852367401, 0.4965093731880188, 0.4907744526863098)
        min_scale: 0.5
        max_scale: 1.0
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115

run:
  agent: image_text_finetune
  max_epoch: 1
  num_workers: 1
  accumulated_gradients: 1
  
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-2
  min_lr: 5e-4 #1e-3
  warmup_lr: 5e-4 #1e-3
  warmup_steps: 50
  iters_per_epoch: 10
  weight_decay: 0.1 #0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42
  output_dir: 'e:\pesquisa_ia\projetos\checkpoints\certifiedgpt'
  amp: True
  resume_ckpt_path: null
  evaluate_only: False
  train_splits: [ "train" ]

  device: "cuda"

#  world_size: 1
#  dist_url: "env://"
#  distributed: False
