model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  # ckpt: '/home/leonardosouza/storage/checkpoints/minigpt-4/prerained_minigpt4_7b.pth'
  ckpt: ${env:MINIGPT_4}
    

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}


datasets:
  vqav2:
    batch_size: 64    
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
        mean: (0.4619535207748413, 0.44102171063423157, 0.4043944478034973)
        std: (0.4985503852367401, 0.4965093731880188, 0.4907744526863098)
        min_scale: 0.5
        max_scale: 1.0
      val:
        name: "blip2_image_val"
        image_size: 224
        mean: (0.4582795202732086, 0.4375796616077423, 0.40068480372428894)
        std: (0.4982563555240631, 0.4960884153842926, 0.4900372326374054)
        min_scale: 0.5
        max_scale: 1.0
    text_processor:
      train:
        name: "blip_caption"
      val:
        name: "blip_caption"    

run:
  agent: image_text_finetune
  max_epoch: 1
  num_workers: 1
  accumulated_gradients: 1
  patience: 10
  noise_level: 0.25
      
  #Consider using other learning rate schedulers for small datasets
  #Exponential Decay:
  #Plateau-Based Decay:      
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5 
  min_lr: 1e-5 
  warmup_lr: 1e-6 
  warmup_steps: 200
  iters_per_epoch: 200
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.999

  seed: 42
  #output_dir: '/home/leonardosouza/storage/checkpoints/certifiedgpt/'
  output_dir: '/home/leonardosouza/checkpoint/certifiedgpt/'
  
  amp: True
  resume_ckpt_path: null
  evaluate: False
  train_splits: ["train"]
  device: "tpu"
  wandb: True
  wandb_api_key: ${env:WANDB_API_KEY}
  wandb_name: "certifiedgpt_finetune_0.25"  

#  world_size: 1
#  dist_url: "env://"
  distributed: True
