model:
  arch: minigpt4
  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '  
  ckpt: ${env:MINIGPT_4}
    

  drop_path_rate: 0
  use_grad_checkpoint: false
  vit_precision: "fp16"
  freeze_vit: true
  has_qformer: true
  freeze_qformer: true
  num_query_token: 32
  low_resource: true
  device_8bit: 0
  
  llama_model: ${env:VICUNA_DIR}
  blip_flant5_pth: ${env:BLIP_FLANT5_PTH}
  eva_vit_g_pth: ${env:EVA_VIT_G_PTH}


# Total batch_size should be multiple of 64
# featue dimension should be a multiple of 128
# https://cloud.google.com/tpu/docs/performance-guide

datasets:
  evqav2:
    batch_size: 52    
    vis_processor:
      test:
        name: "blip2_image_val"
        image_size: 448        
        min_scale: 0.5
        max_scale: 1.0      
    text_processor:
      test:
        name: "blip_caption"      

run:
  agent: image_text_eval
  max_epoch: 15  
  accumulated_gradients: 1
  patience: 1
  noise_level: 0.5
  checkpoint_name: "vqav2_eval_noise_0.5"  
  use_cache: True

  #Consider using other learning rate schedulers for small datasets
  # - Exponential Decay
  # - Plateau-Based Decay

  lr_sched: "linear_warmup_cosine_lr"  
  
  #linear_warmup_cosine_lr -> warmup_lr_schedule
  warmup_steps: 48
  warmup_start_lr: 1e-6   
  warmup_max_lr: 1e-5        
  iters_per_epoch: 48

  #linear_warmup_cosine_lr -> cosine_lr_schedule
  init_lr: 1e-5 
  min_lr: 1e-6
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.999
  seed: 42  
  output_dir: ${env:OUTPUT_DIR}          
  amp: True
  resume_ckpt_path: "vqav2_eval_with_optim_noise_0.5"
  evaluate: False
  train_splits: ["train"]
  has_val_split: true
  device: "tpu"
  wandb: True
  wandb_api_key: ${env:WANDB_API_KEY}
  wandb_name: "vqav2_eval_batch52_noise_0.5" 

  #profile
  enable_profile: False
  profile_logdir: ${env:PROFILE_LOGDIR}  
  profile_epoch: 0
  profile_step: 5
  profiler_port: 9012
  duration_ms: 60000  

# DataLoader
  distributed: True  
  num_workers: 2 # n of workers to load data

# debug
  debug_graph_computation: True
  
